version: "3"

services:
  localhost.localstack.cloud:
    image: localstack/localstack-light:1.0.4
    ports:
      - "4566-4568:4566-4568"
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "./localstack:/docker-entrypoint-initaws.d"
      - "/var/run/docker.sock:/var/run/docker.sock"
    logging:
      options:
        max-size: 1M
        max-file: "10"
    environment:
      - SERVICES=kinesis
      - DEFAULT_REGION=eu-central-1
      - USE_SSL=1
