name: Integration tests - Kafka

on: push

jobs:
  run_kafka_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Publish Docker image
        run: sbt 'project kafka; set Docker / version := "0.0.0"' docker:publishLocal
      - name: Run Docker image
        run: docker run -d -v "$PWD"/.github/workflows/kafka-collector-config:/snowplow/config -p 12345:12345 snowplow/scala-stream-collector-kafka:0.0.0 --config /snowplow/config/config.hocon
      - name: Allow time for collector to start
        run: sleep 30
      - name: Setup integration resources
        run: | 
          (cd integration && docker-compose -f ./docker-compose.yml up -d) 
          sleep 10
          (cd integration && docker-compose logs broker) 
          echo "waiting for kafka to be ready"
          docker exec broker cub kafka-ready -b broker:9092 1 120
          docker exec broker kafka-topics --bootstrap-server broker:9092 --create --topic good && \
          docker exec broker kafka-topics --bootstrap-server broker:9092 --create --topic bad
      - name: Test non-anonymous tracking
        id: non-anonymous
        run: |
          curl -X POST -i http://127.0.0.1:12345/com.snowplowanalytics.snowplow/tp2  -d '{}' 2>&1
      - name: Integration get output
        run: docker exec broker kafka-consumer --topic=good --from-beginning --bootstrap-server broker:9092
      - name: Report outcome
        if: ${{ steps.non-anonymous.outputs.exit_code == 0 && steps.anonymous.outputs.exit_code == 1 }}
        run: echo "All tests successful!"
      - name: Stop Docker container
        run: docker stop $(docker ps -aq)
