name: Integration tests - Kafka

on: push

jobs:
  run_kafka_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v3
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Publish Docker image
        run: sbt 'project kafka; set Docker / version := "0.0.0"' docker:publishLocal
      - name: Run integration test
        run: ./integration_tests/kafka/kafka.sh
