name: Integration tests - Kinesis

on: push

jobs:
  kinesis-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v3
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Kinesis integration tests
        run: make kinesis-integration-tests