name: Integration tests - Kinesis

on: push

jobs:
  kinesis_no_data_lost:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v3
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Initialize the resources and the collector and send data to the collector
        run: '"$PWD"/integration/init.sh kinesis "$PWD"/integration/docker-compose.yml integration.hocon "$PWD"/.github/workflows/integration_tests/no-data-loss/data.txt'
      - name: Read from Kinesis good stream
        run: ./.github/workflows/integration_tests/no-data-loss/consume_kinesis.sh good
      - name: Stop Docker containers
        run: docker stop $(docker ps -aq)