name: telemetryIntegTest

on: push

jobs:
  integ_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v3
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: build
        run: |
          sbt stdout/docker:publishLocal
      - name: run micro
        run: >
          docker run -d
          --name micro
          --mount type=bind,source=$(pwd)/.github/workflows/integration_tests/telemetry/micro_config,destination=/config
          -p 9191:9191 snowplow/snowplow-micro:1.2.1
          --collector-config /config/config.hocon
          --iglu /config/iglu.json
      - name: run collectors
        run: >-
          docker run -d --name enabled --add-host=host.docker.internal:host-gateway -v ${PWD}/.github/workflows/integration_tests/telemetry/sender_config/config.hocon:/snowplow/config.hocon -p 9292:9292 snowplow/scala-stream-collector-stdout --config /snowplow/config.hocon;
          docker run -d --name disabled --add-host=host.docker.internal:host-gateway -v ${PWD}/.github/workflows/integration_tests/telemetry/sender_config/config_disabled.hocon:/snowplow/config.hocon -p 10292:10292 snowplow/scala-stream-collector-stdout --config /snowplow/config.hocon;
          sleep 30;
          docker kill enabled && docker kill disabled
      - name: assess result
        run: |
          pip install requests
          python3 .github/workflows/integration_tests/telemetry/verify_micro_content.py
      - name: clean up
        run: docker stop micro
